# Generated by Django 2.2.11 on 2020-04-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videofeature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usermanagement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='videodetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='videoencoding',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='videoencodingdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='videoencodingformat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='videousertable',
            options={'managed': False},
        ),
    ]
